INSERT INTO user_roles (username, role)
VALUES ('bill', 'ROLE_USER')
INSERT INTO user_roles (username, role)
VALUES ('admin', 'ROLE_ADMIN')
INSERT INTO user_roles (username, role)
VALUES ('dba', 'ROLE_ADMIN')